apiVersion: v2
name: Prometheus-Ashraf
description: Prometheus customized by Ashraf
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: prometheus
    version: 0.1.0
    repository: https://prometheus-community.github.io/helm-charts